CREATE TABLE ROCKETS
    (
        ID integer PRIMARY KEY,
        MODEL varchar(32)
    );

INSERT INTO ROCKETS(ID, MODEL) VALUES (1, 'Angara');
INSERT INTO ROCKETS(ID, MODEL) VALUES (2, 'Soyuz');
INSERT INTO ROCKETS(ID, MODEL) VALUES (3, 'Falcon');
INSERT INTO ROCKETS(ID, MODEL) VALUES (4, 'Topol');

